excluded:
  - Pods
  - .build
  - DerivedData
  - aiaioTests
  - aiaioUITests

disabled_rules:
  - trailing_whitespace
  - todo
  - explicit_self  # Temporarily disabled while we set up CI
  - vertical_whitespace_opening_braces  # Temporarily disabled
  - vertical_whitespace_closing_braces  # Temporarily disabled

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call

analyzer_rules:
  - unused_import

force_cast: error
force_try: error
force_unwrapping: error

line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_comments: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z

nesting:
  type_level:
    warning: 3
    error: 6 