# .swiftlint.yml

# Disable only essential rules
disabled_rules:
  - no_module_imports  # Required for Package.swift
  - trailing_whitespace
  - todo
  - unresolved_import

# Opt-in rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - missing_docs
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces

analyzer_rules:
  - unused_declaration
  - unused_import

force_cast: error
force_try: error
force_unwrapping: error

line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_comments: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z

nesting:
  type_level:
    warning: 3
    error: 6

excluded:
  - .build
  - Package.swift
  - "**/Generated"
  - Pods
  - DerivedData
  - App/aiaio/aiaioTests
  - App/aiaio/aiaioUITests

custom_rules:
  no_module_imports:
    name: "No Module Imports"
    regex: '^import\s+(Logging|Utilities)'
    message: "Do not import internal modules in the same target"
    severity: error
