name: iOS CI

on:
  push:
    branches: [ main, development ]
    paths:
      - 'App/**'
      - '.github/workflows/ios-ci.yml'
  pull_request:
    branches: [ main, development ]
    paths:
      - 'App/**'
      - '.github/workflows/ios-ci.yml'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
      
    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Run SwiftLint
      run: swiftlint lint --strict App/aiaio
      
    - name: Build iOS App
      run: |
        cd App/aiaio
        xcodebuild clean build \
          -scheme aiaio \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=18.2" \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=YES \
          | xcbeautify
          
    - name: Run Tests
      run: |
        cd App/aiaio
        xcodebuild test \
          -scheme aiaio \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=18.2" \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          | xcbeautify

    - name: Verify Strict Concurrency
      run: |
        cd App/aiaio
        if ! grep -q "SWIFT_STRICT_CONCURRENCY = complete" aiaio.xcodeproj/project.pbxproj; then
          echo "Error: Strict concurrency is not enabled"
          exit 1
        fi 